### PR TITLE
removed essentially duplicate color

### PR DESCRIPTION
**Pull request by svanheulen**
The "base4" and "blue" colors were essentially the same color. It was very very hard to see the difference even with my monitor brightness turned all the way up. It wasn't an issue with the vim themes but if your terminal colors are set to match it can cause problems in other applications.

### CODE REVIEW

**Comment by whatyouhide** [comment]
Hey @svanheulen thanks for the contribution, can you include detailed before/after screenshot please?

**Comment by svanheulen** [comment]
I switched all the references of "base4" to "blue" and since they were so similar, there should be no noticeable difference in the theme. I also gave "base4" a new color but it's not actually used anywhere.

Before:
screen_shot_1488379639
After:
screen_shot_1488379485
Before:
before
After:
after
And here's the problem I was having with the old colors, ("base4" text on "blue" background):
example

**Comment by svanheulen** [comment]
Also here's a diff between the before and after so you can see which parts changed:
diff

**Comment by whatyouhide** [comment]
The change looks good, thanks for contributing @svanheulen and sorry for the long wait :)

**Pull request merged**
